name: Setup nodejs
run-name: ${{ github.actor }} doing setup nodejs
on: [push]
jobs:
  Setup-nodejs:
    runs-on: ubuntu-lastest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up nodejs v14
        uses: actions/setup-node@v3
        with: 
          node-version: '14.10.x'
      - name: Check version npm
        run: npm --version
      - name: Install dependencies
        run: npm ci
      - name: Npm run test
        run: npm test